
name: Homepage Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node&Npm
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - name: Install Dependences
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy To Github Page
      uses: peaceiris/actions-gh-pages@v3
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./build
      