
name: Homepage Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node&Npm
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - name: Install Dependences
      run: npm install

    - name: Deploy To Github Page
      run: npm run deploy
      